**Group 5 members:**

Alberto Diaz

Barbara Lorenzo

Bosco Morales

Robert Rivera

## Assignment 1. CAP 4631C. Fall 2024

### Instructions:

Download the file "radiation_clean.csv" from Canvas (especifically from the Assignment 1 section). Open a python notebook in Colab and read this file as a data frame in this notebook (as we have done in class with other csv files). Call this data frame __df_assig1__

The radiation_clean dataset is part of EPA's RadNet Database. It contains the near-real-time environmental radiation data from fixed and deployable air monitors in different locations in the US. It contains data about the level of several radioactive substances in different locations.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
path_radiation_dataset="/content/drive/MyDrive/Colab Notebooks/Machine Learning 1/Module 1/Assignment 1/radiation_clean.csv"

In [ ]:
import pandas as pd

In [ ]:
df_assig1= pd.read_csv(path_radiation_dataset)

__AFTER__ you read the csv file as a data frame, take a look at __df_assig1__ by running the following code cell:

In [ ]:
df_assig1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 606 entries, 0 to 605
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   State           606 non-null    object 
 1   Location        606 non-null    object 
 2   Date Posted     606 non-null    object 
 3   Date Collected  606 non-null    object 
 4   Sample Type     606 non-null    object 
 5   Unit            606 non-null    object 
 6   Ba-140          605 non-null    float64
 7   Co-60           605 non-null    float64
 8   Cs-134          606 non-null    int64  
 9   Cs-136          506 non-null    float64
 10  Cs-137          606 non-null    int64  
 11  I-131           606 non-null    int64  
 12  I-132           606 non-null    int64  
 13  I-133           605 non-null    float64
 14  Te-129          506 non-null    float64
 15  Te-129m         506 non-null    float64
 16  Te-132          606 non-null    int64  
 17  Ba-140.1        0 non-null      flo

__Question 1__ (8 points): Create a Numpy array called _i131_data_ with the data from the column _I-131_ in __df_assig1__.

Note: I-131 (i.e., Iodine-131) is one of many radiactive substances.

Hint: Use the same method we used in class to read the PRCP column from the rain dataset into a NumPy array.

In [ ]:
# Answer question 1 here

i131_data= df_assig1['I-131'].values

In [ ]:
type(i131_data)

numpy.ndarray

__Question 2__ (8 points): Return the first, sixth, and twelfth elements of i131_data. __Write only one line of code__ to answer this question.

In [ ]:
# Answer question 2 here
print(i131_data[:13:5])

[0 0 1]


__Question 3__ (8 points): Return the last five elements of i131_data.

Spring 24: __Write only one line of code__ to answer this question.

In [ ]:
# Answer question 3 here
print(i131_data[-5:])

[6 0 0 0 0]


__Question 4__ (8 points): Return how many times the value of i131_data is between 2 and 4 (both numbers included).

__Write only one line of code__ to answer this question.

In [ ]:
# Answer question 4 here
print(((i131_data >= 2) & (i131_data <= 4)).sum())

25


__Question 5__ (8 points): Return how many times the value of i131_data is either zero or 1. To answer this question, you __CANNOT__ use the symbol < in your answer (the _less than_ symbol). You __must__ answer it without using this symbol.

In [ ]:
# Answer question 5 here
print(((i131_data == 0) | (i131_data == 1)).sum())

515


__Question 6__ (8 points): Return the names of the States where i131_data has been above 2. Use ONLY ONE line of code.

Hint: It is ok if your output shows the same State repeated many times.

In [ ]:
# Answer question 6 here
print(df_assig1.loc[i131_data > 2, 'State'])

54     AK
408    HI
411    MO
415    AR
417    CA
       ..
574    CO
579    CT
585    MI
598    WA
601    CA
Name: State, Length: 82, dtype: object


__Question 7__ (8 points): Return how many times i131_data has a value of zero in California.

Hint: California is recorded as CA in the State colum.

In [ ]:
# Answer question 7 here
print(((df_assig1['State'] == 'CA') & (i131_data == 0)).sum())

31


__Question 8__ (8 points): Write a print statement that returns this message: _The highest registered value of I-131 is:_ FILL IN THE BLANK

where, FILL IN THE BLANK is the actual highest registered value of i131_data.

In [ ]:
# Answer question 8 here
print(f"The highest registered value of I-131 is: {max(i131_data)}")

The highest registered value of I-131 is: 390


__Question 9__ (8 points): Run the following code cell to create an array called q9_array.

In [ ]:
import numpy as np

In [ ]:
q9_array = np.array ([13, 8, 3, 6, 8, 17, 2, 5, 10])

9a) Create a new array called q9_array_sorted that contains the sorted values of q9_array.

In [ ]:
# Answer question 9a here
q9_array_sorted = np.sort(q9_array)
print(q9_array_sorted)

[ 2  3  5  6  8  8 10 13 17]


9b) Create a new array called q9_array_2dim that re-arranges the values of q9_array in a two-dimensional squared array (squared= with the same number of rows and columns).

In [ ]:
# Answer question 9b here
q9_array_2dim = q9_array.reshape(3, 3)
print(q9_array_2dim)

[[13  8  3]
 [ 6  8 17]
 [ 2  5 10]]


In [ ]:
print("Number of dimensions in q9_array:", q9_array.ndim)
print("Number of dimensions in q9_array_2dim:", q9_array_2dim.ndim)

Number of dimensions in q9_array: 1
Number of dimensions in q9_array_2dim: 2


__Question 10__ (8 points): Use NumPy methods to generate the following arrays:

10 a) Generate an array with the numbers from 96 to 0, decreasing in steps of 8 (i.e., 96, 88, 80, ...., 0). Call this array a1.

10 b) Generate an array with the number 2 repeated as many times as the size of array a1. Call this array a2.

10 c) Add the arrays created in a) and b) and save the results in a3. Return the values of a3 (i.e., print the values of a3).

Note: To answer question 10 and create the arrays requested in a, b, and c, you __CANNOT__ enter the values of the arrays manually. You __must__ use the NumPy methods we learned in class to create them.

In [ ]:
# Answer question 10a here
a1 = np.arange(96, -1, -8)
print("Array a1:", a1)

Array a1: [96 88 80 72 64 56 48 40 32 24 16  8  0]


In [ ]:
# Answer question 10b here
a2 = np.full(a1.shape, 2)
print("Array a2:", a2)

Array a2: [2 2 2 2 2 2 2 2 2 2 2 2 2]


In [ ]:
# Concatenate arrays
a3 = np.concatenate((a1, a2))

# Print the concatenated array
print("Array a3:", a3)

Array a3: [96 88 80 72 64 56 48 40 32 24 16  8  0  2  2  2  2  2  2  2  2  2  2  2
  2  2]


__Question 11__ (5 points): Return how many observations were taken at each State. __Write only one line of code__ to answer this question.

In [ ]:
# Answer question 11 here
df_assig1.groupby('State').size()

State
AK       70
AK        1
AL       20
AR       10
AZ        3
CA       42
CNMI     19
CO        6
CT       11
DE        4
FL       11
GA        8
Guam     21
Guam      3
HI       49
IA        4
ID       29
IL        4
KS        9
KY        2
LA        2
MA       10
MD        6
MI        9
MN        8
MO        4
MS        4
MT        2
NC       12
ND        2
NE        2
NH       10
NJ        5
NM        4
NV       23
NY       22
OH       19
OK        2
OR        6
PA       15
PA        1
RI        1
RI        1
SC        8
TN       56
TX        7
UT        9
VA        6
VT        1
WA       19
WI        2
WV        2
dtype: int64

__Question 12__ (5 points): Return the __df_assig1__ data frame sorted by the 'Date Collected'. Show the latest collected observations first. __Write only one line of code__ to answer this question.

In [ ]:
# Answer question 12 here
df_assig1.sort_values(by='Date Collected', ascending=False)

State     Location Date Posted Date Collected     Sample Type    Unit  \
577    PA   Harrisburg  2011-05-24     2011-04-30  Precipitation    pCi/l   
570    NC    Charlotte  2011-05-24     2011-04-29  Precipitation    pCi/l   
584    TN    Knoxville  2011-05-24     2011-04-29  Precipitation    pCi/l   
568    MA       Boston  2011-05-24     2011-04-29  Precipitation    pCi/l   
599    OH  Painesville  2011-05-24     2011-04-29  Precipitation    pCi/l   
..    ...          ...         ...            ...             ...     ...   
539    OH  Painesville  2011-04-04     2011-03-15   Precipitation   pCi/l   
510    TN    Nashville  2011-04-13     2011-03-15   Precipitation   pCi/l   
213    CA    Riverside  2011-03-30     2011-03-15      Air Filter  pCi/m3   
543    CA     Richmond  2011-04-04     2011-03-15   Precipitation   pCi/l   
24     CA      Anaheim  2011-03-30     2011-03-11      Air Filter  pCi/m3   

     Ba-140  Co-60  Cs-134  Cs-136  Cs-137  I-131  I-132  I-133  Te-129  \
577     0.0    0.0       0     0.0       0      0      0    0.0     0.0   
570     0.0    0.0       0     0.0       0      0      0    0.0     0.0   
584     0.0    0.0       0     0.0       0      0      0    0.0     0.0   
568     0.0    0.0       0     0.0       0      0      0    0.0     0.0   
599     0.0    0.0       0     0.0       0      0      0    0.0     0.0   
..      ...    ...     ...     ...     ...    ...    ...    ...     ...   
539     0.0    0.0       0     NaN       0      0      0    0.0     NaN   
510     0.0    0.0       0     0.0       0      0      0    0.0     0.0   
213     0.0    0.0       0     NaN       0      0      0    0.0     NaN   
543     0.0    0.0       0     NaN       0      0      0    0.0     NaN   
24      0.0    0.0       0     NaN       0      0      0    0.0     NaN   

     Te-129m  Te-132  Ba-140.1  
577      0.0       0       NaN  
570      0.0       0       NaN  
584      0.0       0       NaN  
568      0.0       0       NaN  
599      0.0       0       NaN  
..       ...     ...       ...  
539      NaN       0       NaN  
510      0.0       0       NaN  
213      NaN       0       NaN  
543      NaN       0       NaN  
24       NaN       0       NaN  

[606 rows x 18 columns]

__Question 13__ (5 points): Return the __df_assig1__ data frame only showing the samples taken in Miami. Miami is one of the values from the column 'Location'. __Write only one line of code__ to answer this question.

In [ ]:
# Asnwer question 13 here
df_assig1[df_assig1['Location'] == 'Miami']

State Location Date Posted Date Collected     Sample Type   Unit  Ba-140  \
312    FL    Miami  2011-04-08     2011-03-29  Drinking Water  pCi/l     0.0   

     Co-60  Cs-134  Cs-136  Cs-137  I-131  I-132  I-133  Te-129  Te-129m  \
312    0.0       0     0.0       0      0      0    0.0     0.0      0.0   

     Te-132  Ba-140.1  
312       0       NaN

__Question 14__ (5 points): Return the average concentration of 'I-131' found on each state. __Write only one line of code__ to answer this question.

In [ ]:
# Answer question 14 here
df_assig1.groupby('State')['I-131'].mean()

State
AK        0.157143
AK        0.000000
AL        1.050000
AR        5.900000
AZ        1.000000
CA        7.119048
CNMI      0.105263
CO        8.333333
CT        5.454545
DE        0.000000
FL       15.636364
GA        2.125000
Guam      0.047619
Guam      0.000000
HI        0.591837
IA        0.000000
ID       23.068966
IL        0.000000
KS       24.444444
KY        0.000000
LA        0.000000
MA       14.400000
MD        0.000000
MI        2.777778
MN        7.125000
MO        0.750000
MS        0.000000
MT        0.000000
NC        7.500000
ND        0.000000
NE        0.000000
NH        7.100000
NJ        0.000000
NM        0.000000
NV        0.173913
NY        3.227273
OH        2.789474
OK        0.000000
OR       14.500000
PA        0.733333
PA        1.000000
RI        0.000000
RI        0.000000
SC        0.000000
TN        7.535714
TX        0.000000
UT       24.444444
VA        1.500000
VT        0.000000
WA       10.368421
WI        0.000000
WV        0.000000
Name: I-131, dtype: float64